# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
        required: true
        type: string
        default: "v0.1"

env:
  BUILD_TAG: 123
 
jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - name: x86
            type: 64
            device: generic
          - name: rockchip
            type: armv8
            device: friendlyarm_nanopi-r2s

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        echo "RELEASE_TAG=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

    - name: Test
      run: |
        mkdir -p bb
        echo "aaaaa" > bb/aa.img.gz
        echo "bbbbb" > bb/bb.img.gz
        mkdir -p aa
        if ! ls -l | grep -q 'img.gz$'; then
          echo yes
        fi

        if ! ls -l | grep -q 'img.gz$'; then
          echo yes
        fi
